spring:
  datasource:
    url: jdbc:mysql://localhost:3306/phoneshop
    username: admin
    password: 1234
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8888

